# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u66f8\u7c4d\u540d')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='\u51fa\u7248\u793e')),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='\u30da\u30fc\u30b8\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='\u30b3\u30e1\u30f3\u30c8')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='formtest.Book', verbose_name='\u66f8\u7c4d')),
            ],
        ),
    ]
